---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default
  adapter:  mysql
  database: loser
  username: loser
  password: insecure
  host: localhost
 
test:
  <<:       *defaults
  database: loser_test
 
production:
  <<:       *defaults
  database: loser_prod
 
rake:
  <<: *defaults
